name: dispatch
on: 
  workflow_dispatch: 
    inputs:
      logLevel:
        type: choice
        default: warning
        options:
        - info
        - warning
        - debug
      environment:
        type: environment
      matrix:
        type: string

jobs: 
  log-the-inputs: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        LogLevel: ${{ fromJSON(inputs.logLevel) }}
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: test123456
        run: | 
          echo "Log level: $LEVEL" 
          echo "Tags: $TAGS" 
          echo "Environment: $ENVIRONMENT" 
        env: 
          LEVEL: ${{ matrix.LogLevel }} 
          TAGS: ${{ inputs.tags }} 
          ENVIRONMENT: ${{ inputs.environment }}