name: dispatch
on: 
  workflow_dispatch: 
    inputs:
      logLevel:
        type: choice
        default: warning
        options:
        - info
        - warning
        - debug
      environment:
        type: environment

jobs: 
  log-the-inputs: 
    runs-on: ubuntu-latest 
    steps:
      - name: test123456
        run: | 
          echo "Log level: $LEVEL" 
          echo "Tags: $TAGS" 
          echo "Environment: $ENVIRONMENT" 
        env: 
          LEVEL: ${{ inputs.logLevel }} 
          TAGS: ${{ inputs.tags }} 
          ENVIRONMENT: ${{ inputs.environment }}
